# Generated by Django 5.2.7 on 2025-11-03 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='biodata',
            name='download_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='biodata',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='biodata',
            name='template_choice',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='biodata',
            name='user_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='biodata',
            name='user_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='biodata',
            name='user_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
