# Generated by Django 5.2.7 on 2025-11-18 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0002_biodata_download_link_biodata_is_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='biodata',
            name='payment_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='payments/'),
        ),
    ]
