# Generated by Django 5.2.7 on 2025-12-31 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0003_biodata_payment_screenshot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biodata',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='biodata',
            name='payment_screenshot',
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(blank=True, max_length=255)),
                ('payment_screenshot', models.ImageField(blank=True, null=True, upload_to='payments/')),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('biodata', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='biodata.biodata')),
            ],
        ),
    ]
