# Generated by Django 5.2.7 on 2026-01-01 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0004_remove_biodata_is_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='biodata',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Admin approval status after payment and email sent'),
        ),
    ]
