# Generated by Django 5.2.7 on 2026-01-02 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0005_biodata_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='biodata',
            name='payment_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='payments/'),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
